config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :listings do
    resource :likes, only: [:create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "about", to: "static#about"
  # Defines the root path route ("/")
  root "listings#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/physical_address_formatter.rb
module PhysicalAddressFormatter
  extend ActiveSupport::Concern

  def has_address?
    !(street_address.blank? && address_2.blank? && city.blank? && state.blank? && zipcode.blank?)
  end

  def city_state_zip
    [city, state, zipcode].reject(&:blank?).join(" ")
  end

  def address_line_1
    [street_address].reject(&:blank?).join(", ")
  end

  def formatted_address
    [street_address, city_state_zip].reject(&:blank?).join(", ")
  end
end

app/models/concerns/searchable.rb
module Searchable
  extend ActiveSupport::Concern

  included do
    scope :with_city, ->(city) {
      where("lower(city) LIKE ?", "%#{city.downcase}%") if city.present?
    }

    scope :with_state, ->(state_code) {
      state = US_STATES[state_code&.to_sym]
      where("lower(state) LIKE ?", "%#{state.downcase}%") if state.present?
    }

    scope :with_bedrooms, ->(bedrooms) {
      where("bedrooms = ?", bedrooms) if bedrooms.present?
    }

    scope :with_bathrooms, ->(bathrooms) {
      where("bathrooms = ?", bathrooms) if bathrooms.present?
    }
  end

  class_methods do
    def search(params={})
      sort_column =
        params[:sort]
          .presence_in(%w{ by_state by_bedrooms by_price by_bathrooms }) || "by_id"

      sort_direction =
        sort_column == "by_state" ? :asc : :desc

      self
        .with_city(params[:city])
        .with_state(params[:state])
        .with_bedrooms(params[:bedrooms])
        .with_bathrooms(params[:bathrooms])
        .order(sort_column.delete("by_") => sort_direction)
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :listing
  belongs_to :user
end

app/models/listing.rb
class Listing < ApplicationRecord
  include PhysicalAddressFormatter
  include Searchable

  has_one_attached :photo do |attachable|
    attachable.variant :thumb, resize_to_limit: [450, 450]
  end

  has_many :likes, dependent: :destroy

  def liked_by?(user)
    likes.where(user: user).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  helper_method :current_user

  def current_user
    User.first
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_listing

  def create
    return if existing_like

    @like = Like.create!(user: current_user, listing: @listing)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to request.referrer } # fallback for non-turbo clients i.e., when JS is disabled
    end
  end

  def destroy
    return unless (like = existing_like)

    like.destroy!

    respond_to do |format|
      format.turbo_stream { render :create }
      format.html { redirect_to request.referrer } # fallback for non-turbo clients i.e., when JS is disabled
    end
  end

  private

  def find_listing
    @listing = Listing.find(params[:listing_id])
  end

  def existing_like
    current_user.likes.where(listing: @listing).first
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @pagy, @listings = pagy(Listing.search(params))
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to listing_url(@listing), notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:street_address, :city, :state, :bathrooms, :bedrooms, :sqft, :price, :zipcode)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def about
    sleep 3
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def header_link(text = nil, link = "#", selected = false, &block)
    text = capture(&block) if block

    default_classes = "inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium"
    selected_classes = "border-indigo-500 text-gray-900"
    unselected_classes = "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700"
      tag.a(class: class_names(default_classes, selected ? selected_classes : unselected_classes), href: link) do
        text
      end
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>ListingHotwireDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-full">
    <div class="min-h-full">
      <nav class="border-b border-gray-200 bg-white">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div class="flex h-16 justify-between">
            <div class="flex">
              <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
                <%= header_link "Listings", listings_path, controller_name == "listings" %>
                <%= header_link "Users", users_path, controller_name == "users" %>
                <%= header_link "Search" %>
                <%= header_link "About", about_path, controller_name == "static" && action_name == "about" %>
              </div>
            </div>
            <div class="hidden sm:ml-6 sm:flex sm:items-center">
              <span class="border-2 rounded-xl p-2" id="likes_count" data-turbo-permanent>
                <%= Like.count %>
              </span>

              <div class="relative ml-3">
                <div>
                  <button type="button" class="flex max-w-xs items-center rounded-full bg-white text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                    <%= current_user.name %>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>

      <div class="py-10">
        <header>
          <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <h1 class="text-3xl font-bold leading-tight tracking-tight text-gray-900">
              <%= yield :page_heading %>
            </h1>
          </div>
        </header>
        <main>
          <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div class="px-4 py-8 sm:px-0">
              <%= yield %>
            </div>
          </div>
        </main>
      </div>
    </div>
  </body>
</html>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.replace @listing, @listing %>

<!-- This is the same as -->
<%#= turbo_stream.replace @listing,
                         partial: "listing/listing", locals: { listing: @listing } %>

<!-- This is the same as -->
<!--<turbo-stream action="replace" target="<%#= dom_id @listing %>">-->
<!--  <template>-->
    <%#= render partial: "listing/listing", locals: { listing: @listing } %>
<!--  </template>-->
<!--</turbo-stream>-->



<!--Update likes_count-->
<%= turbo_stream.update "likes_count" do %>
  <%= Like.count %>
<% end %>

app/views/listings/_form.html.erb
<%= form_with(model: listing, class: "contents") do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :city %>
    <%= form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :state %>
    <%= form.text_field :state, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bathrooms %>
    <%= form.text_field :bathrooms, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bedrooms %>
    <%= form.number_field :bedrooms, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :sqft %>
    <%= form.number_field :sqft, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :zipcode %>
    <%= form.text_field :zipcode, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/listings/_listing.html.erb
<%= tag.div dom_id(listing) do %>
  <div id="<%= dom_id listing %>" class="col-span-1 flex flex-col divide-y divide-gray-200 rounded-lg bg-white text-center shadow">
    <%= Time.zone.now.strftime("at %H:%M:%S") %>
    <%= link_to listing, class: "flex flex-1 flex-col p-8", data: { turbo_frame: "_top" } do %>
      <%= image_tag url_for(listing.photo.variant(:thumb)), class: "mx-auto h-32 w-32 flex-shrink-0 rounded-full" %>
      <h3 class="mt-6 text-sm font-medium text-gray-900"><%= listing.address_line_1 %></h3>
      <dl class="mt-1 flex flex-grow flex-col justify-between">
        <dt class="sr-only">Title</dt>
        <dd class="text-sm text-gray-500"><%= listing.city_state_zip %></dd>
        <dt class="sr-only">Role</dt>
        <dd class="mt-3">
          <span class="rounded-full bg-green-100 px-2 py-1 text-xs font-medium text-green-800">
            <%= number_to_currency listing.price, precision: 0 %>
          </span>
        </dd>
      </dl>
    <% end %>
    <div>
      <div class="-mt-px flex divide-x divide-gray-200">
        <div class="flex w-0 flex-1">
          <div class="relative inline-flex w-0 flex-1 items-center justify-center rounded-br-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500">
            <span class="ml-3">
              <%= pluralize(listing.bedrooms, 'bed') %>
            </span>
          </div>
        </div>
        <div class="-ml-px flex w-0 flex-1">
          <div class="relative inline-flex w-0 flex-1 items-center justify-center rounded-br-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500">
            <span class="ml-3">
              <%= pluralize(listing.bathrooms, 'bath') %>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div>
      <% if listing.liked_by? current_user %>
        <%= button_to "Remove", listing_likes_path(listing_id: listing), method: :delete, class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" %>
      <% else %>
        <%= button_to "Add", listing_likes_path(listing_id: listing), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing listing</h1>

  <%= render "form", listing: @listing %>

  <%= link_to "Show this listing", @listing, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to listings", listings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/listings/index.html.erb
<div class="w-full" id="listings_index">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Listings</h1>
    <%= link_to 'New listing', new_listing_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div class="my-4 relative">
    <%= form_with(url: listings_path, method: :get, class: "space-y-2 sm:flex sm:space-x-2 sm:space-y-0 items-center justify-center",
                  data: {
                    turbo_frame: "results",
                    turbo_action: "advance",
                    controller: "auto-submit-form",
                    action: "input->auto-submit-form#submitForm"
                  }) do |f| %>
      <div>
        <%= f.search_field :city, placeholder: 'City...',
                           value: params[:city], class: "mb-0 text-base bg-gray-100 text-gray-700" %>
      </div>
      <div>
        <%= f.select :bedrooms, (1..6).to_a,
                     { include_blank: "Any Bedrooms", selected: params[:bedrooms] }, { class: "mb-0 text-base bg-gray-100 text-gray-700" } %>
      </div>
      <div>
        <%= f.select :bathrooms, (1..4).to_a,
                     { include_blank: "Any Bathrooms", selected: params[:bathrooms] }, { class: "mb-0 text-base bg-gray-100 text-gray-700" } %>
      </div>
      <div>
        <%= f.select :state, US_STATES.invert.sort,
                     { include_blank: "Any State", selected: params[:state] }, { class: "mb-0 text-base bg-gray-100 text-gray-700" } %>
      </div>
      <div>
        <%= f.select :sort,
                     [["By State", "by_state"], ["By Bedrooms", "by_bedrooms"], ["By Price", "by_price"], ["By Bathrooms", "by_bathrooms"]],
                     { include_blank: "Sort By", selected: params[:sort] }, { class: "mb-0 text-base bg-gray-100 text-gray-700" } %>
      </div>
      <div>
        <%= f.submit "Search", class: "ml-6 p-2 tracking-wider bg-gray-200 text-gray-800 border border-gray-400 active:bg-gray-700 hover:bg-gray-400 focus:border-gray-700 focus:ring-2 focus:ring-offset-2 focus:ring-gray-300" %>
      </div>
    <% end %>
  </div>


  <%= turbo_frame_tag "results", data: { turbo_action: "advance" } do %>
    <div id="listings" role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 my-6">
      <%= render @listings %>
    </div>

    <%== pagy_nav(@pagy) %>
  <% end %>

</div>

app/views/listings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New listing</h1>

  <%= render "form", listing: @listing %>

  <%= link_to 'Back to listings', listings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/listings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
      <div class="px-4 py-5 sm:px-6">
        <h3 class="text-lg font-medium leading-6 text-gray-900">Listing # <%= @listing.id %></h3>
        <p class="mt-1 max-w-2xl text-sm text-gray-500">Listing information</p>
      </div>
      <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
        <dl class="sm:divide-y sm:divide-gray-200">
          <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">Address</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= @listing.formatted_address %></dd>
          </div>
          <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">Price</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= number_to_currency @listing.price, precision: 2 %></dd>
          </div>
          <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">Beds</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= @listing.bedrooms %></dd>
          </div>
          <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">Bathrooms</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= @listing.bathrooms %></dd>
          </div>
          <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">SQFT</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0"><%= @listing.sqft %></dd>
          </div>
          <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">Attachments</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
              <%= image_tag url_for(@listing.photo.variant(:thumb)), class: "mx-auto w-128 h-128 flex-shrink-0" %>
            </dd>
          </div>
        </dl>
      </div>
    </div>

    <%= link_to 'Edit this listing', edit_listing_path(@listing), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this listing', listing_path(@listing), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to listings', listings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= user.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= user.name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this user', edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <%= render @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>